### ISSUE TITLE
AssemblyInfo.cs is missing.

### ISSUE THREAD

**Issue by jmpotvin** [wet-boew/wet-boew-dotnet-controls#2]
Trying to troubleshoot this problem:

Assembly 'WetControls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' contains a Web resource with name 'WetControls.Scripts.wetscripts.js', but does not contain an embedded resource with name 'WetControls.Scripts.wetscripts.js'. 

If you have one, could you add the AssemblyInfo.cs that you have defined for your project please.

**Comment by jpesant** [comment]
I justed add the AssemblyInfo file.
